name: DefaultSpawner
version: 1.0
main: com.eightonegulf.mc.defaultspawner.Plugin

commands:
  defaultspawner:
    description: Manage default spawn point
    usage: /defaultspawner
    permission: defaultspawner
permissions:
  defaultspawner:
    default: op